cache = true
cache_exclude_status = "429,500.."
files_from = ".lycheeinputs"
include_fragments = "full"
max_cache_age = "1d"
max_concurrency = 16
max_redirects = 10
max_retries = 2
method = "get"
no_progress = true
retry_wait_time = 2
timeout = 20
accept_timeouts = false
exclude_all_private = true
exclude_path = [ "node_modules", "src-tauri/target", "target" ]
host_concurrency = 4
include_mail = false
scheme = [ "http", "https", "file" ]
